version: '3'
services:
  fcron:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      TZ: America/Los_Angeles
      PREFIX: TEST_CRON
      DEBUG: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cnt_1:
    image: debian
    tty: true
    environment:
      TEST_CRON_0: ''
      TEST_CRON_1: '@daily touch /tmp/daily'
      TEST_CRON_2: '*/1 * * * * touch /tmp/minutely'
      TEST_CRON_3: '0 */1 * * * touch /tmp/hourly'
      TEST_CRON_4: '&runas(irc) */1 * * * * touch /tmp/minutely.irc'
      TEST_CRON_5: 'This is a big steaming load of garbage'
      TEST_CRON_6: 'VAR1 = "foo"'
      TEST_CRON_7: 'VAR2=bar'
      TEST_CRON_8: '*/1 * * * * export >/tmp/vars'
      TEST_CRON_START_0: '@ 1d'


