version: '3'
services:
  fcron:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      TIMEZONE: America/Los_Angeles
      FCRON_ENV_PREFIX: TEST_CRON
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cnt_1:
    image: debian
    tty: true
    environment:
      TEST_CRON_0: ''
      TEST_CRON_1: '@daily touch /tmp/daily'
      TEST_CRON_2: '*/1 * * * * touch /tmp/minutely'
      TEST_CRON_3: '0 */1 * * * touch /tmp/hourly'
      TEST_CRON_4: '&runas(irc) */1 * * * * touch /tmp/minutely.irc'

      
