# This Dockerfile is used for development/testing. It mimics the normal one,
# but creates an image roughly 3x the size. However, it is more tolerant of
# incremental change. Changing one line in a script does not hit the network
# or rebuild fcron as it would in the normal version.
FROM alpine:3.11

RUN apk update \
 && apk add --no-cache build-base perl shadow wget tini ca-certificates tzdata python3 msmtp

ENV FCRON_VERSION=3.2.1 \
    DOCKER_GEN_VERSION=0.7.4

RUN cd /tmp \
 && wget http://fcron.free.fr/archives/fcron-$FCRON_VERSION.src.tar.gz \
 && wget https://github.com/jwilder/docker-gen/releases/download/$DOCKER_GEN_VERSION/docker-gen-linux-amd64-$DOCKER_GEN_VERSION.tar.gz

ENTRYPOINT ["/sbin/tini", "/opt/bin/start.sh"]
COPY opt/lib/requirements.txt /opt/lib/requirements.txt
RUN pip3 install -r /opt/lib/requirements.txt
COPY opt/bin/runjob.c /opt/bin/runjob.c
COPY opt/bin/install.sh /opt/bin/install.sh
RUN /bin/sh /opt/bin/install.sh
ADD opt /opt
RUN chmod 755 /opt/bin/*.sh /opt/lib/*.py
